### ISSUE TITLE
the project configuration is incorrect.

### ISSUE THREAD

**Issue by Josecep** [Moxibyte/MoxPP#2]
The custom configuration files are all concatenated, which is a bit unusual.
![1684586830401](https://github.com/Moxibyte/MoxPP/assets/115909081/e3ec601a-d929-4b81-a614-9c64390383b4)
![1684586870695](https://github.com/Moxibyte/MoxPP/assets/115909081/b58f2ef0-6dfc-467e-b2ed-3829deb415be)

**Comment by Ohjurot** [comment]
It seems like premake5 is not correctly resolving a relative path from conans absolute path output. Can you send me the content of thees files:
- `dependencies\conan_fmt_vars_release_x86_64.premake5.lua`
- `dependencies\conandeps.premake5.lua`
- `conanfile.py`

Can the application still be build?

**Comment by Josecep** [comment]
> 似乎 premake5 没有正确解析来自柯南绝对路径输出的相对路径。你能把你的文件内容发给我吗：
> 
> * `dependencies\conan_fmt_vars_release_x86_64.premake5.lua`
> * `dependencies\conandeps.premake5.lua`
[zip.zip](https://github.com/Moxibyte/MoxPP/files/11522738/zip.zip)

> * `conanfile.py`
> 
> 应用程序仍然可以构建吗？

**Comment by Ohjurot** [comment]
Ok, from the files, I can see that conan generated invalid files. I have tests this and was able to reproduce the issue in version 2.0.5 (Just releases a few days a go). Seems like that every new release of conan2 breaks premake again...

For now, I would recommend you to downgrade to 2.0.4 (`pip install conan==2.0.4 --force-reinstall`). I developed the generator for 2.0.2, and it works (as it seems) only up to 2.0.4. 

I will so how fast I can contribute a patch to conan, but from my experience it will not be before 2.0.7.

**Comment by Ohjurot** [comment]
OK as it seems the bug was fixed fast. I hope the conan Team will find some time and will be able to merge my PR as soon as possible. So maybe we can get it already for 2.0.6

**Comment by Josecep** [comment]
Hello, would you be interested in creating a tutorial on using conan and xmake together?

**Comment by Ohjurot** [comment]
@Josecep just for your information: My PR was merged into the conan development branch and will be available on 2.0.6
