### ISSUE TITLE
On mox init got error 

### ISSUE THREAD

**Issue by EndijsOgrins** [Moxibyte/MoxPP#4]
Got this error on: mox init
conan install: error: ambiguous option: --deploy=full_deploy could match --deployer, --deployer-folder
ERROR: Exiting with code: 2

i manage to fix it with changing init.py:
'--deploy=full_deploy',
to
'--deployer=full_deploy',

**Comment by Ohjurot** [comment]
Fixed in 9e0e1f310c31b87eb78a4331962227622515887a
